/* 
Editorial
*/
INSERT INTO `editorial`(`nombre`, `direccion`, `estadoAuditoria`, `fechaIngreso`, `usuarioIngreso`, `fechaModifica`, `usuarioModifica`, `fechaElimina`, `usuarioElimina`) VALUES 
('Sin Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones de la U',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('McGraw Hill',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('MPES',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Paraninfo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Oxford University Press',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Cambridge',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Macro',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Empresa Editora Macro EIRL',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Harla S.A.',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ministerio de justicia Del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('El Conejo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Imprenta Mariscal',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Escobar Impresores',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Juridica del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Juridica Grijley',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Pearson',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Fundacion Universitaria Luis Amigo para Colombia',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Biblioteca Juridica',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ecoe Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Prentice Hall',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('The Frontiers Of Management',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Publingraf',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('La Verdad Presente',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Verbo Divino',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Luppa',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Longman Literature',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Diorki',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alfaomega',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Foras-Creatividad Sin Limites',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Walters Klinwers',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Gráfica Cervantes',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Panorama Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Sudamericana',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Cevallos Librería Jurídica',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Cengage Learning',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Mestas',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Impresos Andinos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Richmond Publishing',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Plutón Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial de la Universidad Tecnica Particular de Loja',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Panamericana',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Heliasta Education',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Adriana Gutierrez',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Nuevo Amanecer',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Librería Larousse',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('4 Media',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Carlos Morlás Espinoza',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ecoc Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Addison-Wesley Iberoamericana S.A.',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('PUCE',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Servilibros',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Grupo Santillana',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Patmos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Esic Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('V&R Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Exitotial-Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Academia Editores',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Garceta',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('El Telegrafo EP',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Norma',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Jurídica Del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones ENI',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Alejandra Adoum',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('San Marcos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Tierra Viva',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Reverté',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Planeta S.A.',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Scholastic',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Macmillan',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Libresa',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ecg-Universidad del Norte',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Edino',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Guillermo Arosemena',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Soboc Grafic',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('UEES',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Pontificia Universidad Católica del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Talleres de la Corporación de Estudios y Publicaciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Legales',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('APEEM Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Fondo Educativo Interamericano',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Limusa',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Grijalbo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Miró',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Universidad Central de Venezuela',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Facultad de Ciencias U.C.V',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alfaguara',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editora Géminis Ltda',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Bantam Dell',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Spire',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Macmillan Publishers Limited',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Grupo Editorial Norma',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Castillo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones SM',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Santillana Ediciones Generales',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Renuevo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Culturales Paidos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Guadarrama',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Microsoft Corporation',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Pueblo y Educación',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Bertha Escobar Ruiz',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Palomino EIRL',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Iberoamericana',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Nauta',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Hispanoamericano',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Fundacion Nuestros Jovenes',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Era Dinamica',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Naomi Rhode',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Corporacion de Estudios y Publicaciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Centro de Publicaciones Nacionales',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('MM Publications',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Neungyule Education',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Sal Terrae',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial ABC',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial UDLA',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Tallpa',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editogran',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Tiznada',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Carlos Mortensen Bonilla',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('UCSG',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Indexada Latindex',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Carlos Zepeda Chehaibar',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Indice Latino Americano',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Cambrigde',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Luis Fernandez M',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Fausto Garces,Nelson Robelly,Manuel Burgos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Martin J. Morant',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Abel Cruz M',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Rudolh F. Verderber',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Arthur I. Vogel',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Gobierno de la Republica Del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Lathi',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alfed V. John E. Jeffrey D.',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Hernan Beati',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Vicente Rojas Jose Ñagato',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Enfoque A la Familia',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Oscar Wilde',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Maria Fernanda Heredia',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Jenny Dooley',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alfredo Gomez Cerda',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Peter Navarro',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Jose Mauro de Vasconcelos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Leonidas Aguilar Aguilar',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alex Lima Murillo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Jose Medina U',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Livia Palacios Lopez',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Diego Merino Naranjo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Norma D Mullen P Charles Brown',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('CICR',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Instituto Superior Tecnologico Cotopaxi',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ministerio de Justiica, Derechos Humanos Y Cultos',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editorial Vida',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Alpha Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('6 CDS',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Britannica Inc',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Urano',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediloja',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Zonalegal',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Edype',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Cyan Proyectos Editoriales',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Thomson',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Universidad Casa Grande',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Poligrafica SA',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Abrayas',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Zamora',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Debolsillo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Random House',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Proyecto Cultural Municipal',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Minga Educativa',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Superintendencia de Bancos Del Ecuador',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Business Publications',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('CFN',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Senefelde',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('UG',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Don Bosco',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Pixeles',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Corporacion Editoria Nacional',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Grupo Editorial Trebol',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Raquel Gomez H',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Oceano',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Grupo Editorial Patria',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Pudeleco Legislacion Economica',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Planeta Colombiana',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Express Publishing',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Lideditoria',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Hispano Y Europea',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ingenios',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Francisco Guzman',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Delta Publicaciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Editext',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Profit',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Maipue Ediciones',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('UTPL',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('CEP',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Piramide',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Dovaal',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ediciones Cultural',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Marcombo',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Edicion EMD ',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Academia APOL',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Casa Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Diaz de Santos ',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Trillas',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Columbia SC',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Doctrina Juridica',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Edipuce',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('LID Editorial',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Universidad de Azuay Casa Editora',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ministerio de Industrias y Productividad',null,1,NOW(),'SERVER',Null,Null,Null,Null),
('Ministerio de Agricultura, Ganadería',null,1,NOW(),'SERVER',Null,Null,Null,Null);